import type { Plugin, ResolvedConfig } from 'vite'
import { mkdir, writeFile } from 'node:fs/promises'
import { isAbsolute, join, resolve } from 'node:path'
import process from 'node:process'

const DEFAULT_DIR_NAME = '.flow-dock'
const DEFAULT_PLACEHOLDER_NAME = '.keep'
const DEFAULT_PLACEHOLDER_CONTENT = 'generated by flow-dock-kit\n'

interface OutputOptionsLike {
  dir?: string
}

export interface EnsureFlowDockDirOptions {
  dirName?: string
  writePlaceholder?: boolean
  placeholderName?: string
  placeholderContent?: string
}

export interface FlowDockKitOptions extends EnsureFlowDockDirOptions {
  root?: string
  writeToRootOnBuild?: boolean
  fallbackWriteToOutDir?: boolean
}

function sanitizeDirName(dirName: string): string {
  const sanitized = dirName
    .replace(/\\/g, '/')
    .replace(/^\/+/, '')
    .replace(/\/+$/, '')

  return sanitized || DEFAULT_DIR_NAME
}

function sanitizeFileName(fileName: string): string {
  const sanitized = fileName
    .replace(/\\/g, '/')
    .replace(/^\/+/, '')

  return sanitized || DEFAULT_PLACEHOLDER_NAME
}

function resolveRoot(configRoot: string | undefined, optionRoot: string | undefined): string {
  if (optionRoot)
    return resolve(optionRoot)

  if (configRoot)
    return resolve(configRoot)

  return process.cwd()
}

function resolveOutDir(config: ResolvedConfig): string {
  const { outDir } = config.build
  return isAbsolute(outDir) ? outDir : resolve(config.root, outDir)
}

function resolveWriteOutDir(config: ResolvedConfig | undefined, outputOptions: OutputOptionsLike): string | null {
  if (outputOptions.dir) {
    if (isAbsolute(outputOptions.dir))
      return outputOptions.dir

    return resolve(config?.root ?? process.cwd(), outputOptions.dir)
  }

  if (!config)
    return null

  return resolveOutDir(config)
}

function toEnsureOptions(options: EnsureFlowDockDirOptions = {}): Required<EnsureFlowDockDirOptions> {
  return {
    dirName: sanitizeDirName(options.dirName ?? DEFAULT_DIR_NAME),
    writePlaceholder: options.writePlaceholder ?? true,
    placeholderName: sanitizeFileName(options.placeholderName ?? DEFAULT_PLACEHOLDER_NAME),
    placeholderContent: options.placeholderContent ?? DEFAULT_PLACEHOLDER_CONTENT,
  }
}

async function ensureDir(root: string, options: Required<EnsureFlowDockDirOptions>): Promise<string> {
  const targetDir = join(root, options.dirName)
  await mkdir(targetDir, { recursive: true })

  if (options.writePlaceholder) {
    const placeholderFile = join(targetDir, options.placeholderName)
    await writeFile(placeholderFile, options.placeholderContent, { encoding: 'utf8' })
  }

  return targetDir
}

export async function ensureFlowDockDir(root?: string, options: EnsureFlowDockDirOptions = {}): Promise<string> {
  const normalizedOptions = toEnsureOptions(options)
  const targetRoot = root ? resolve(root) : process.cwd()
  return ensureDir(targetRoot, normalizedOptions)
}

// export default function flowDockKit(options: FlowDockKitOptions = {}): Plugin {
//   const pluginName = 'vite-plugin-flow-dock-kit'
//   const normalizedOptions = toEnsureOptions(options)
//   const writeToRootOnBuild = options.writeToRootOnBuild ?? true
//   const fallbackWriteToOutDir = options.fallbackWriteToOutDir ?? true
//   const emittedAssetPath = `${normalizedOptions.dirName}/${normalizedOptions.placeholderName}`
//   let resolvedConfig: ResolvedConfig | undefined

//   function warn(message: string, error?: unknown): void {
//     const detail = error instanceof Error ? `: ${error.message}` : ''
//     const text = `[${pluginName}] ${message}${detail}`
//     if (resolvedConfig?.logger)
//       resolvedConfig.logger.warn(text)
//     else
//       console.warn(text)
//   }

//   async function ensureAtRoot(): Promise<void> {
//     const root = resolveRoot(resolvedConfig?.root, options.root)
//     await ensureDir(root, normalizedOptions)
//   }

//   async function ensureAtOutDir(outDir: string): Promise<void> {
//     await ensureDir(outDir, normalizedOptions)
//   }

//   return {
//     name: pluginName,

//     async configResolved(config) {
//       resolvedConfig = config
//       const shouldEnsureRoot = config.command === 'serve' || writeToRootOnBuild
//       if (!shouldEnsureRoot)
//         return

//       try {
//         await ensureAtRoot()
//       }
//       catch (error) {
//         warn('failed to ensure root .flow-dock directory', error)
//       }
//     },

//     async configureServer() {
//       try {
//         await ensureAtRoot()
//       }
//       catch (error) {
//         warn('failed to ensure .flow-dock directory in dev server', error)
//       }
//     },

//     async buildStart() {
//       if (!writeToRootOnBuild)
//         return

//       try {
//         await ensureAtRoot()
//       }
//       catch (error) {
//         warn('failed to ensure .flow-dock directory in buildStart', error)
//       }
//     },

//     generateBundle() {
//       if (!normalizedOptions.writePlaceholder)
//         return

//       this.emitFile({
//         type: 'asset',
//         fileName: emittedAssetPath,
//         source: normalizedOptions.placeholderContent,
//       })
//     },

//     async writeBundle(outputOptions) {
//       if (!fallbackWriteToOutDir)
//         return

//       const outDir = resolveWriteOutDir(resolvedConfig, outputOptions)
//       if (!outDir)
//         return

//       try {
//         await ensureAtOutDir(outDir)
//       }
//       catch (error) {
//         warn('failed to ensure .flow-dock directory in outDir', error)
//       }
//     },
//   }
// }
