export function renderServerFacadeTemplate() {
  return `/* eslint-disable */
// Generated by flow-dock-kit. Do not edit.

export {
  defineRouterHandle,
  isRouterHandle,
} from '../server/driver/define-router-handle.driver'

export type {
  AnyRouterHandle,
  RouterError,
  RouterEvent,
  RouterFailure,
  RouterHandle,
  RouterHandleOptions,
  RouterHandler,
  RouterMethod,
  RouterRequestMeta,
  RouterRequestPayload,
  RouterResponse,
  RouterSuccess,
} from '../server/driver/define-router-handle.driver'

export {
  defineSchemaHandle,
  isSchemaHandle,
} from '../server/driver/define-schema-handle.driver'

export type {
  SchemaHandle,
  SchemaHandleOptions,
  SchemaIndexDefinition,
  SchemaOperationOptions,
  SchemaQuery,
  SchemaTransactionOptions,
} from '../server/driver/define-schema-handle.driver'

export {
  defineMiddlewareHandle,
  isMiddlewareHandle,
} from '../server/driver/define-middleware-handle.driver'

export type {
  RouterMiddleware,
  RouterNext,
} from '../server/driver/define-middleware-handle.driver'

export {
  definePluginHandle,
  isPluginHandle,
} from '../server/driver/define-plugin-handle.driver'

export type {
  RuntimePlugin,
  RuntimePluginHooks,
} from '../server/driver/define-plugin-handle.driver'

export type {
  RouterContext,
  RouterRequestTransaction,
  RouterSender,
  RouterTransactionMode,
  RouterTransactionStatus,
  RuntimeTraceContext,
} from '../server/runtime/types'
`
}
