// import fs from 'node:fs/promises'
// import path from 'node:path'
// import process from 'node:process'

// export interface FlowDockKitOptions {
//   root?: string // 项目根（用于解析 .flow-dock 的位置），默认为 process.cwd()
//   dirName?: string // 要创建的目录名，默认为 '.flow-dock'
//   writePlaceholder?: boolean // 是否写入占位文件，默认为 true
// }

// /**
//  * createFlowDockKitDriver
//  * 返回一个轻量的 Vite 插件（也可直接作为脚本调用 ensureFlowDockDir）
//  */
// export function createFlowDockKitDriver(opts: FlowDockKitOptions = {}) {
//   const root = opts.root ? path.resolve(opts.root) : process.cwd()
//   const dirName = opts.dirName || '.flow-dock'
//   const placeholder = opts.writePlaceholder ?? true

//   async function ensureFlowDockDir() {
//     const target = path.join(root, dirName)
//     try {
//       await fs.mkdir(target, { recursive: true })
//       if (placeholder) {
//         const file = path.join(target, 'placeholder.txt')
//         await fs.writeFile(file, `generated by flow-dock-kit\n`, { encoding: 'utf8' })
//       }
//     }
//     catch (err) {
//       // 不要阻塞构建，记录或忽略即可
//       // console.warn('[flow-dock-kit] ensureFlowDockDir failed:', err);
//     }
//   }

//   // 也导出可直接调用的确保函数
//   const plugin = {
//     name: 'flow-dock-kit',
//     // 不设置 apply，默认在 dev 和 build 都会生效
//     async configResolved() {
//       // 在配置解析后就尝试创建目录（尽早）
//       await ensureFlowDockDir()
//     },
//     async configureServer(server: any) {
//       // dev 时确保目录
//       await ensureFlowDockDir()
//     },
//     async buildStart() {
//       // build 时确保目录
//       await ensureFlowDockDir()
//     },
//   }

//   return plugin
// }

// export async function ensureFlowDockDir(root?: string, dirName = '.flow-dock') {
//   const targetRoot = root ? path.resolve(root) : process.cwd()
//   const target = path.join(targetRoot, dirName)
//   await fs.mkdir(target, { recursive: true })
// }
